### ISSUE TITLE
Bug: The Extensions menu is broken when this extension is installed.

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/SparqlExtension#15]
### Problem ###
When this extension is installed, it breaks the Extension popup-menu.

Broken popup-menu/button:
![image](https://user-images.githubusercontent.com/12217525/178404155-fe53f7f7-ef64-431a-81e8-6dd7c5c47053.png)

Working:
![image](https://user-images.githubusercontent.com/12217525/178404549-d089808e-0386-4b8d-8c03-d59feb4413b7.png)

Regards, Antoine

**Comment by WaltonG** [comment]
I noticed that in my development environment
