### ISSUE TITLE
The HTTP request to the Query Service should be sent from the back-end

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/SparqlExtension#18]
The HTTP request to the Query Service could be sent from the back-end, and not the Front-End (JavaScript). In most scenario, it may be better.

https://github.com/OpenRefine/SparqlExtension/blob/95784b3577395bf3f13faabae0e318f4ec9dd649/module/scripts/index/sparql-source-ui.js#L27

**Comment by WaltonG** [comment]
Sure. Then we will have to do away with the Sparql.js

**Comment by antoine2711** [comment]
Nice. Good work.

Regards, Antoine
