### ISSUE TITLE
Trying to query ArtsData SPARQL end-point fails

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/SparqlExtension#27]
### Description of the problem

End-point: `http://kg.artsdata.ca/sparql/`

```
# Upcoming events in Artsdata.ca

PREFIX schema: <http://schema.org/>
SELECT DISTINCT  ?start ?status ?mode (sample(?label) as ?name)  (sample(?url) as ?webpage)
WHERE {
  ?e a schema:Event ;
     schema:startDate ?start ;
     schema:name ?label ;
     schema:url ?url ;
     schema:eventStatus ?status ;
     schema:eventAttendanceMode ?mode .
  FILTER(?start > '2022-08-10T01:47:07.569Z'^^xsd:dateTime)
} 
GROUP BY ?start ?status ?mode
LIMIT 1000
```

This will trigger an error: « Unable to parse preview ».

**Comment by WaltonG** [comment]
From the console logs it seems the query didn't return a valid json string. 

`Exception::{}com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`

Am looking into it

**Comment by WaltonG** [comment]
@antoine2711 The correct enpoint has to be provided which is `http://kg.artsdata.ca/query `not `http://kg.artsdata.ca/sparql/`

`http://kg.artsdata.ca/sparql/` is used by the provided YASGUI user interface  while remote sparql clients use `http://kg.artsdata.ca/query `

**Comment by antoine2711** [comment]
> @antoine2711 The correct enpoint has to be provided which is `http://kg.artsdata.ca/query `not `http://kg.artsdata.ca/sparql/`
> 
> `http://kg.artsdata.ca/sparql/` is used by the provided YASGUI user interface while remote sparql clients use `http://kg.artsdata.ca/query `

Oups. Good catch. Thanks. Antoine

**Comment by antoine2711** [comment]
But still @WaltonG, we could improve the error message.

A.

**Comment by WaltonG** [comment]
@antoine2711 Since an error can be caused by any type exception  I think a generalised error message `Unable to parse preview` is ideal rather than displaying backend error message. Any suggestions ?
